Update file - fatal error fix
Due to:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2005] Unknown MySQL server host 'localhostdbname=XXXXX' (110)' in /home/X/public_html/X/inc/plugins/invitation_generator.php:53 Stack trace: #0 /home/X/public_html/X/inc/plugins/invitation_generator.php(53): PDO->__construct('mysql:host=loca...', 'X', 'X') #1 {main} thrown in /home/X/public_html/X/inc/plugins/invitation_generator.php on line 53

I'm green in coding so I looked it up http://culttt.com/2012/10/01/roll-your-own-pdo-php-class/ and I found that we miss a ";" in the 53rd line of the code. Now it works fine.